// ============================================================================
// Complete U.S. Constitution Text – Sourced from National Archives
// Source: https://www.archives.gov/founding-docs/constitution-transcript
// Retrieved: 2025-01-15 | Verification: Official Government Source
// ============================================================================

import { Section } from './types'

/**
 * All sections from the U.S. Constitution including the Preamble,
 * Articles I–VII, and all 27 Amendments (Bill of Rights + subsequent).
 *
 * Canonical citations follow Bluebook format.
 * Text is from the National Archives official transcript.
 */
export const usConstitutionSections: Section[] = [
  // ── Preamble ──────────────────────────────────────────────────────────
  {
    id: 'us-const-preamble',
    documentId: 'us-constitution',
    title: 'Preamble',
    number: 'Preamble',
    text: 'We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America.',
    canonicalCitation: 'U.S. Const. pmbl.',
    order: 0,
    topicTags: ['popular-sovereignty', 'founding-principles'],
  },

  // ── Article I – The Legislative Branch ────────────────────────────────
  {
    id: 'us-const-art1',
    documentId: 'us-constitution',
    title: 'Article I – The Legislative Branch',
    number: 'I',
    text: 'All legislative Powers herein granted shall be vested in a Congress of the United States, which shall consist of a Senate and House of Representatives.',
    canonicalCitation: 'U.S. Const. art. I, § 1',
    order: 1,
    topicTags: ['separation-of-powers', 'legislative-power'],
  },
  {
    id: 'us-const-art1-s2',
    documentId: 'us-constitution',
    title: 'Article I, Section 2 – The House of Representatives',
    number: 'I.2',
    text: 'The House of Representatives shall be composed of Members chosen every second Year by the People of the several States, and the Electors in each State shall have the Qualifications requisite for Electors of the most numerous Branch of the State Legislature.\n\nNo Person shall be a Representative who shall not have attained to the Age of twenty five Years, and been seven Years a Citizen of the United States, and who shall not, when elected, be an Inhabitant of that State in which he shall be chosen.\n\nRepresentatives and direct Taxes shall be apportioned among the several States which may be included within this Union, according to their respective Numbers, which shall be determined by adding to the whole Number of free Persons, including those bound to Service for a Term of Years, and excluding Indians not taxed, three fifths of all other Persons. The actual Enumeration shall be made within three Years after the first Meeting of the Congress of the United States, and within every subsequent Term of ten Years, in such Manner as they shall by Law direct. The Number of Representatives shall not exceed one for every thirty Thousand, but each State shall have at Least one Representative.\n\nThe House of Representatives shall chuse their Speaker and other Officers; and shall have the sole Power of Impeachment.',
    canonicalCitation: 'U.S. Const. art. I, § 2',
    parentSectionId: 'us-const-art1',
    order: 2,
    topicTags: ['legislative-power', 'representation', 'impeachment'],
  },
  {
    id: 'us-const-art1-s3',
    documentId: 'us-constitution',
    title: 'Article I, Section 3 – The Senate',
    number: 'I.3',
    text: 'The Senate of the United States shall be composed of two Senators from each State, chosen by the Legislature thereof, for six Years; and each Senator shall have one Vote.\n\nImmediately after they shall be assembled in Consequence of the first Election, they shall be divided as equally as may be into three Classes. The Seats of the Senators of the first Class shall be vacated at the Expiration of the second Year, of the second Class at the Expiration of the fourth Year, and of the third Class at the Expiration of the sixth Year, so that one third may be chosen every second Year.\n\nNo Person shall be a Senator who shall not have attained to the Age of thirty Years, and been nine Years a Citizen of the United States, and who shall not, when elected, be an Inhabitant of that State for which he shall be chosen.\n\nThe Vice President of the United States shall be President of the Senate, but shall have no Vote, unless they be equally divided.\n\nThe Senate shall have the sole Power to try all Impeachments. When the President of the United States is tried, the Chief Justice shall preside: And no Person shall be convicted without the Concurrence of two thirds of the Members present.\n\nJudgment in Cases of Impeachment shall not extend further than to removal from Office, and disqualification to hold and enjoy any Office of honor, Trust or Profit under the United States: but the Party convicted shall nevertheless be liable and subject to Indictment, Trial, Judgment and Punishment, according to Law.',
    canonicalCitation: 'U.S. Const. art. I, § 3',
    parentSectionId: 'us-const-art1',
    order: 3,
    topicTags: ['legislative-power', 'impeachment', 'senate'],
  },
  {
    id: 'us-const-art1-s4',
    documentId: 'us-constitution',
    title: 'Article I, Section 4 – Elections',
    number: 'I.4',
    text: 'The Times, Places and Manner of holding Elections for Senators and Representatives, shall be prescribed in each State by the Legislature thereof; but the Congress may at any time by Law make or alter such Regulations, except as to the Places of chusing Senators.\n\nThe Congress shall assemble at least once in every Year, and such Meeting shall be on the first Monday in December, unless they shall by Law appoint a different Day.',
    canonicalCitation: 'U.S. Const. art. I, § 4',
    parentSectionId: 'us-const-art1',
    order: 4,
    topicTags: ['elections', 'congressional-procedure'],
  },
  {
    id: 'us-const-art1-s5',
    documentId: 'us-constitution',
    title: 'Article I, Section 5 – Rules of Proceedings',
    number: 'I.5',
    text: 'Each House shall be the Judge of the Elections, Returns and Qualifications of its own Members, and a Majority of each shall constitute a Quorum to do Business; but a smaller Number may adjourn from day to day, and may be authorized to compel the Attendance of absent Members, in such Manner, and under such Penalties as each House may provide.\n\nEach House may determine the Rules of its Proceedings, punish its Members for disorderly Behaviour, and, with the Concurrence of two thirds, expel a Member.\n\nEach House shall keep a Journal of its Proceedings, and from time to time publish the same, excepting such Parts as may in their Judgment require Secrecy; and the Yeas and Nays of the Members of either House on any question shall, at the Desire of one fifth of those Present, be entered on the Journal.\n\nNeither House, during the Session of Congress, shall, without the Consent of the other, adjourn for more than three days, nor to any other Place than that in which the two Houses shall be sitting.',
    canonicalCitation: 'U.S. Const. art. I, § 5',
    parentSectionId: 'us-const-art1',
    order: 5,
    topicTags: ['congressional-procedure', 'quorum', 'legislative-power'],
  },
  {
    id: 'us-const-art1-s6',
    documentId: 'us-constitution',
    title: 'Article I, Section 6 – Compensation & Privileges',
    number: 'I.6',
    text: 'The Senators and Representatives shall receive a Compensation for their Services, to be ascertained by Law, and paid out of the Treasury of the United States. They shall in all Cases, except Treason, Felony and Breach of the Peace, be privileged from Arrest during their Attendance at the Session of their respective Houses, and in going to and returning from the same; and for any Speech or Debate in either House, they shall not be questioned in any other Place.\n\nNo Senator or Representative shall, during the Time for which he was elected, be appointed to any civil Office under the Authority of the United States, which shall have been created, or the Emoluments whereof shall have been encreased during such time; and no Person holding any Office under the United States, shall be a Member of either House during his Continuance in Office.',
    canonicalCitation: 'U.S. Const. art. I, § 6',
    parentSectionId: 'us-const-art1',
    order: 6,
    topicTags: ['speech-or-debate-clause', 'congressional-compensation', 'separation-of-powers'],
  },
  {
    id: 'us-const-art1-s7',
    documentId: 'us-constitution',
    title: 'Article I, Section 7 – Revenue Bills, Presentment',
    number: 'I.7',
    text: 'All Bills for raising Revenue shall originate in the House of Representatives; but the Senate may propose or concur with Amendments as on other Bills.\n\nEvery Bill which shall have passed the House of Representatives and the Senate, shall, before it become a Law, be presented to the President of the United States; If he approve he shall sign it, but if not he shall return it, with his Objections to that House in which it shall have originated, who shall enter the Objections at large on their Journal, and proceed to reconsider it. If after such Reconsideration two thirds of that House shall agree to pass the Bill, it shall be sent, together with the Objections, to the other House, by which it shall likewise be reconsidered, and if approved by two thirds of that House, it shall become a Law. But in all such Cases the Votes of both Houses shall be determined by Yeas and Nays, and the Names of the Persons voting for and against the Bill shall be entered on the Journal of each House respectively. If any Bill shall not be returned by the President within ten Days (Sundays excepted) after it shall have been presented to him, the Same shall be a Law, in like Manner as if he had signed it, unless the Congress by their Adjournment prevent its Return, in which Case it shall not be a Law.\n\nEvery Order, Resolution, or Vote to which the Concurrence of the Senate and House of Representatives may be necessary (except on a question of Adjournment) shall be presented to the President of the United States; and before the Same shall take Effect, shall be approved by him, or being disapproved by him, shall be repassed by two thirds of the Senate and House of Representatives, according to the Rules and Limitations prescribed in the Case of a Bill.',
    canonicalCitation: 'U.S. Const. art. I, § 7',
    parentSectionId: 'us-const-art1',
    order: 7,
    topicTags: ['presentment-clause', 'veto-power', 'revenue-bills', 'checks-and-balances', 'how-a-bill-becomes-law'],
  },
  {
    id: 'us-const-art1-s8',
    documentId: 'us-constitution',
    title: 'Article I, Section 8 – Powers of Congress',
    number: 'I.8',
    text: 'The Congress shall have Power To lay and collect Taxes, Duties, Imposts and Excises, to pay the Debts and provide for the common Defence and general Welfare of the United States; but all Duties, Imposts and Excises shall be uniform throughout the United States;\n\nTo borrow Money on the credit of the United States;\n\nTo regulate Commerce with foreign Nations, and among the several States, and with the Indian Tribes;\n\nTo establish an uniform Rule of Naturalization, and uniform Laws on the subject of Bankruptcies throughout the United States;\n\nTo coin Money, regulate the Value thereof, and of foreign Coin, and fix the Standard of Weights and Measures;\n\nTo provide for the Punishment of counterfeiting the Securities and current Coin of the United States;\n\nTo establish Post Offices and post Roads;\n\nTo promote the Progress of Science and useful Arts, by securing for limited Times to Authors and Inventors the exclusive Right to their respective Writings and Discoveries;\n\nTo constitute Tribunals inferior to the supreme Court;\n\nTo define and punish Piracies and Felonies committed on the high Seas, and Offences against the Law of Nations;\n\nTo declare War, grant Letters of Marque and Reprisal, and make Rules concerning Captures on Land and Water;\n\nTo raise and support Armies, but no Appropriation of Money to that Use shall be for a longer Term than two Years;\n\nTo provide and maintain a Navy;\n\nTo make Rules for the Government and Regulation of the land and naval Forces;\n\nTo provide for calling forth the Militia to execute the Laws of the Union, suppress Insurrections and repel Invasions;\n\nTo provide for organizing, arming, and disciplining, the Militia, and for governing such Part of them as may be employed in the Service of the United States, reserving to the States respectively, the Appointment of the Officers, and the Authority of training the Militia according to the discipline prescribed by Congress;\n\nTo exercise exclusive Legislation in all Cases whatsoever, over such District (not exceeding ten Miles square) as may, by Cession of particular States, and the Acceptance of Congress, become the Seat of the Government of the United States, and to exercise like Authority over all Places purchased by the Consent of the Legislature of the State in which the Same shall be, for the Erection of Forts, Magazines, Arsenals, dock-Yards, and other needful Buildings;\n\nTo make all Laws which shall be necessary and proper for carrying into Execution the foregoing Powers, and all other Powers vested by this Constitution in the Government of the United States, or in any Department or Officer thereof.',
    canonicalCitation: 'U.S. Const. art. I, § 8',
    parentSectionId: 'us-const-art1',
    order: 8,
    topicTags: ['enumerated-powers', 'commerce-clause', 'necessary-and-proper', 'taxing-power'],
  },
  {
    id: 'us-const-art1-s9',
    documentId: 'us-constitution',
    title: 'Article I, Section 9 – Limits on Congress',
    number: 'I.9',
    text: 'The Privilege of the Writ of Habeas Corpus shall not be suspended, unless when in Cases of Rebellion or Invasion the public Safety may require it.\n\nNo Bill of Attainder or ex post facto Law shall be passed.\n\nNo Capitation, or other direct, Tax shall be laid, unless in Proportion to the Census or enumeration herein before directed to be taken.\n\nNo Tax or Duty shall be laid on Articles exported from any State.\n\nNo Preference shall be given by any Regulation of Commerce or Revenue to the Ports of one State over those of another: nor shall Vessels bound to, or from, one State, be obliged to enter, clear, or pay Duties in another.\n\nNo Money shall be drawn from the Treasury, but in Consequence of Appropriations made by Law; and a regular Statement and Account of the Receipts and Expenditures of all public Money shall be published from time to time.\n\nNo Title of Nobility shall be granted by the United States.',
    canonicalCitation: 'U.S. Const. art. I, § 9',
    parentSectionId: 'us-const-art1',
    order: 9,
    topicTags: ['habeas-corpus', 'limits-on-power', 'bill-of-attainder'],
  },
  {
    id: 'us-const-art1-s10',
    documentId: 'us-constitution',
    title: 'Article I, Section 10 – Limits on States',
    number: 'I.10',
    text: 'No State shall enter into any Treaty, Alliance, or Confederation; grant Letters of Marque and Reprisal; coin Money; emit Bills of Credit; make any Thing but gold and silver Coin a Tender in Payment of Debts; pass any Bill of Attainder, ex post facto Law, or Law impairing the Obligation of Contracts, or grant any Title of Nobility.\n\nNo State shall, without the Consent of the Congress, lay any Imposts or Duties on Imports or Exports, except what may be absolutely necessary for executing its inspection Laws: and the net Produce of all Duties and Imposts, laid by any State on Imports or Exports, shall be for the Use of the Treasury of the United States; and all such Laws shall be subject to the Revision and Controul of the Congress.\n\nNo State shall, without the Consent of Congress, lay any Duty of Tonnage, keep Troops, or Ships of War in time of Peace, enter into any Agreement or Compact with another State, or with a foreign Power, or engage in War, unless actually invaded, or in such imminent Danger as will not admit of delay.',
    canonicalCitation: 'U.S. Const. art. I, § 10',
    parentSectionId: 'us-const-art1',
    order: 10,
    topicTags: ['federalism', 'limits-on-states', 'contracts-clause'],
  },

  // ── Article II – The Executive Branch ─────────────────────────────────
  {
    id: 'us-const-art2',
    documentId: 'us-constitution',
    title: 'Article II – The Executive Branch',
    number: 'II',
    text: 'The executive Power shall be vested in a President of the United States of America. He shall hold his Office during the Term of four Years, and, together with the Vice President, chosen for the same Term, be elected, as follows:\n\nEach State shall appoint, in such Manner as the Legislature thereof may direct, a Number of Electors, equal to the whole Number of Senators and Representatives to which the State may be entitled in the Congress: but no Senator or Representative, or Person holding an Office of Trust or Profit under the United States, shall be appointed an Elector.\n\nThe Congress may determine the Time of chusing the Electors, and the Day on which they shall give their Votes; which Day shall be the same throughout the United States.\n\nNo Person except a natural born Citizen, or a Citizen of the United States, at the time of the Adoption of this Constitution, shall be eligible to the Office of President; neither shall any Person be eligible to that Office who shall not have attained to the Age of thirty five Years, and been fourteen Years a Resident within the United States.\n\nIn Case of the Removal of the President from Office, or of his Death, Resignation, or Inability to discharge the Powers and Duties of the said Office, the Same shall devolve on the Vice President, and the Congress may by Law provide for the Case of Removal, Death, Resignation or Inability, both of the President and Vice President, declaring what Officer shall then act as President, and such Officer shall act accordingly, until the Disability be removed, or a President shall be elected.\n\nThe President shall, at stated Times, receive for his Services, a Compensation, which shall neither be increased nor diminished during the Period for which he shall have been elected, and he shall not receive within that Period any other Emolument from the United States, or any of them.\n\nBefore he enter on the Execution of his Office, he shall take the following Oath or Affirmation:—"I do solemnly swear (or affirm) that I will faithfully execute the Office of President of the United States, and will to the best of my Ability, preserve, protect and defend the Constitution of the United States."',
    canonicalCitation: 'U.S. Const. art. II, § 1',
    order: 20,
    topicTags: ['separation-of-powers', 'executive-power', 'electoral-college'],
  },
  {
    id: 'us-const-art2-s2',
    documentId: 'us-constitution',
    title: 'Article II, Section 2 – Presidential Powers',
    number: 'II.2',
    text: 'The President shall be Commander in Chief of the Army and Navy of the United States, and of the Militia of the several States, when called into the actual Service of the United States; he may require the Opinion, in writing, of the principal Officer in each of the executive Departments, upon any Subject relating to the Duties of their respective Offices, and he shall have Power to grant Reprieves and Pardons for Offences against the United States, except in Cases of Impeachment.\n\nHe shall have Power, by and with the Advice and Consent of the Senate, to make Treaties, provided two thirds of the Senators present concur; and he shall nominate, and by and with the Advice and Consent of the Senate, shall appoint Ambassadors, other public Ministers and Consuls, Judges of the supreme Court, and all other Officers of the United States, whose Appointments are not herein otherwise provided for, and which shall be established by Law.\n\nThe President shall have Power to fill up all Vacancies that may happen during the Recess of the Senate, by granting Commissions which shall expire at the End of their next Session.',
    canonicalCitation: 'U.S. Const. art. II, § 2',
    parentSectionId: 'us-const-art2',
    order: 22,
    topicTags: ['commander-in-chief', 'treaty-power', 'appointments', 'pardons'],
  },
  {
    id: 'us-const-art2-s3',
    documentId: 'us-constitution',
    title: 'Article II, Section 3 – Presidential Duties',
    number: 'II.3',
    text: 'He shall from time to time give to the Congress Information of the State of the Union, and recommend to their Consideration such Measures as he shall judge necessary and expedient; he may, on extraordinary Occasions, convene both Houses, or either of them, and in Case of Disagreement between them, with Respect to the Time of Adjournment, he may adjourn them to such Time as he shall think proper; he shall receive Ambassadors and other public Ministers; he shall take Care that the Laws be faithfully executed, and shall Commission all the Officers of the United States.',
    canonicalCitation: 'U.S. Const. art. II, § 3',
    parentSectionId: 'us-const-art2',
    order: 23,
    topicTags: ['state-of-the-union', 'take-care-clause', 'executive-duty'],
  },
  {
    id: 'us-const-art2-s4',
    documentId: 'us-constitution',
    title: 'Article II, Section 4 – Impeachment',
    number: 'II.4',
    text: 'The President, Vice President and all civil Officers of the United States, shall be removed from Office on Impeachment for, and Conviction of, Treason, Bribery, or other high Crimes and Misdemeanors.',
    canonicalCitation: 'U.S. Const. art. II, § 4',
    parentSectionId: 'us-const-art2',
    order: 24,
    topicTags: ['impeachment', 'accountability'],
  },

  // ── Article III – The Judicial Branch ──────────────────────────────────
  {
    id: 'us-const-art3',
    documentId: 'us-constitution',
    title: 'Article III – The Judicial Branch',
    number: 'III',
    text: 'The judicial Power of the United States, shall be vested in one supreme Court, and in such inferior Courts as the Congress may from time to time ordain and establish. The Judges, both of the supreme and inferior Courts, shall hold their Offices during good Behaviour, and shall, at stated Times, receive for their Services, a Compensation, which shall not be diminished during their Continuance in Office.',
    canonicalCitation: 'U.S. Const. art. III, § 1',
    order: 30,
    topicTags: ['separation-of-powers', 'judicial-power', 'judicial-independence'],
  },
  {
    id: 'us-const-art3-s2',
    documentId: 'us-constitution',
    title: 'Article III, Section 2 – Judicial Power Scope',
    number: 'III.2',
    text: 'The judicial Power shall extend to all Cases, in Law and Equity, arising under this Constitution, the Laws of the United States, and Treaties made, or which shall be made, under their Authority;—to all Cases affecting Ambassadors, other public Ministers and Consuls;—to all Cases of admiralty and maritime Jurisdiction;—to Controversies to which the United States shall be a Party;—to Controversies between two or more States;—between a State and Citizens of another State;—between Citizens of different States;—between Citizens of the same State claiming Lands under Grants of different States, and between a State, or the Citizens thereof, and foreign States, Citizens or Subjects.\n\nIn all Cases affecting Ambassadors, other public Ministers and Consuls, and those in which a State shall be Party, the supreme Court shall have original Jurisdiction. In all the other Cases before mentioned, the supreme Court shall have appellate Jurisdiction, both as to Law and Fact, with such Exceptions, and under such Regulations as the Congress shall make.\n\nThe Trial of all Crimes, except in Cases of Impeachment, shall be by Jury; and such Trial shall be held in the State where the said Crimes shall have been committed; but when not committed within any State, the Trial shall be at such Place or Places as the Congress may by Law have directed.',
    canonicalCitation: 'U.S. Const. art. III, § 2',
    parentSectionId: 'us-const-art3',
    order: 32,
    topicTags: ['judicial-power', 'jurisdiction', 'jury-trial'],
  },
  {
    id: 'us-const-art3-s3',
    documentId: 'us-constitution',
    title: 'Article III, Section 3 – Treason',
    number: 'III.3',
    text: 'Treason against the United States, shall consist only in levying War against them, or in adhering to their Enemies, giving them Aid and Comfort. No Person shall be convicted of Treason unless on the Testimony of two Witnesses to the same overt Act, or on Confession in open Court.\n\nThe Congress shall have Power to declare the Punishment of Treason, but no Attainder of Treason shall work Corruption of Blood, or Forfeiture except during the Life of the Person attainted.',
    canonicalCitation: 'U.S. Const. art. III, § 3',
    parentSectionId: 'us-const-art3',
    order: 33,
    topicTags: ['treason', 'criminal-law', 'constitutional-crime'],
  },

  // ── Article IV – States' Relations ────────────────────────────────────
  {
    id: 'us-const-art4',
    documentId: 'us-constitution',
    title: 'Article IV – States\' Relations',
    number: 'IV',
    text: 'Section 1. Full Faith and Credit shall be given in each State to the public Acts, Records, and judicial Proceedings of every other State. And the Congress may by general Laws prescribe the Manner in which such Acts, Records and Proceedings shall be proved, and the Effect thereof.',
    canonicalCitation: 'U.S. Const. art. IV, § 1',
    order: 40,
    topicTags: ['full-faith-and-credit', 'federalism'],
  },
  {
    id: 'us-const-art4-s2',
    documentId: 'us-constitution',
    title: 'Article IV, Section 2 – Privileges & Immunities, Extradition',
    number: 'IV.2',
    text: 'The Citizens of each State shall be entitled to all Privileges and Immunities of Citizens in the several States.\n\nA Person charged in any State with Treason, Felony, or other Crime, who shall flee from Justice, and be found in another State, shall on Demand of the executive Authority of the State from which he fled, be delivered up, to be removed to the State having Jurisdiction of the Crime.\n\nNo Person held to Service or Labour in one State, under the Laws thereof, escaping into another, shall, in Consequence of any Law or Regulation therein, be discharged from such Service or Labour, but shall be delivered up on Claim of the Party to whom such Service or Labour may be due.',
    canonicalCitation: 'U.S. Const. art. IV, § 2',
    parentSectionId: 'us-const-art4',
    order: 42,
    topicTags: ['privileges-and-immunities', 'extradition', 'fugitive-clause'],
  },
  {
    id: 'us-const-art4-s3',
    documentId: 'us-constitution',
    title: 'Article IV, Section 3 – New States, Federal Property',
    number: 'IV.3',
    text: 'New States may be admitted by the Congress into this Union; but no new State shall be formed or erected within the Jurisdiction of any other State; nor any State be formed by the Junction of two or more States, or Parts of States, without the Consent of the Legislatures of the States concerned as well as of the Congress.\n\nThe Congress shall have Power to dispose of and make all needful Rules and Regulations respecting the Territory or other Property belonging to the United States; and nothing in this Constitution shall be so construed as to Prejudice any Claims of the United States, or of any particular State.',
    canonicalCitation: 'U.S. Const. art. IV, § 3',
    parentSectionId: 'us-const-art4',
    order: 43,
    topicTags: ['new-states', 'federal-property', 'territory-clause'],
  },
  {
    id: 'us-const-art4-s4',
    documentId: 'us-constitution',
    title: 'Article IV, Section 4 – Guarantee Clause',
    number: 'IV.4',
    text: 'The United States shall guarantee to every State in this Union a Republican Form of Government, and shall protect each of them against Invasion; and on Application of the Legislature, or of the Executive (when the Legislature cannot be convened) against domestic Violence.',
    canonicalCitation: 'U.S. Const. art. IV, § 4',
    parentSectionId: 'us-const-art4',
    order: 44,
    topicTags: ['guarantee-clause', 'republican-government', 'protection-against-invasion'],
  },

  // ── Article V – Amendment Process ─────────────────────────────────────
  {
    id: 'us-const-art5',
    documentId: 'us-constitution',
    title: 'Article V – Amendment Process',
    number: 'V',
    text: 'The Congress, whenever two thirds of both Houses shall deem it necessary, shall propose Amendments to this Constitution, or, on the Application of the Legislatures of two thirds of the several States, shall call a Convention for proposing Amendments, which, in either Case, shall be valid to all Intents and Purposes, as Part of this Constitution, when ratified by the Legislatures of three fourths of the several States, or by Conventions in three fourths thereof, as the one or the other Mode of Ratification may be proposed by the Congress; Provided that no Amendment which may be made prior to the Year One thousand eight hundred and eight shall in any Manner affect the first and fourth Clauses in the Ninth Section of the first Article; and that no State, without its Consent, shall be deprived of its equal Suffrage in the Senate.',
    canonicalCitation: 'U.S. Const. art. V',
    order: 50,
    topicTags: ['amendment-process', 'constitutional-change'],
  },

  // ── Article VI – Supremacy Clause ─────────────────────────────────────
  {
    id: 'us-const-art6',
    documentId: 'us-constitution',
    title: 'Article VI – Supremacy Clause',
    number: 'VI',
    text: 'All Debts contracted and Engagements entered into, before the Adoption of this Constitution, shall be as valid against the United States under this Constitution, as under the Confederation.\n\nThis Constitution, and the Laws of the United States which shall be made in Pursuance thereof; and all Treaties made, or which shall be made, under the Authority of the United States, shall be the supreme Law of the Land; and the Judges in every State shall be bound thereby, any Thing in the Constitution or Laws of any State to the Contrary notwithstanding.\n\nThe Senators and Representatives before mentioned, and the Members of the several State Legislatures, and all executive and judicial Officers, both of the United States and of the several States, shall be bound by Oath or Affirmation, to support this Constitution; but no religious Test shall ever be required as a Qualification to any Office or public Trust under the United States.',
    canonicalCitation: 'U.S. Const. art. VI, cl. 2',
    order: 60,
    topicTags: ['supremacy-clause', 'federal-preemption', 'oath-of-office'],
  },

  // ── Article VII – Ratification ────────────────────────────────────────
  {
    id: 'us-const-art7',
    documentId: 'us-constitution',
    title: 'Article VII – Ratification',
    number: 'VII',
    text: 'The Ratification of the Conventions of nine States, shall be sufficient for the Establishment of this Constitution between the States so ratifying the Same.\n\nDone in Convention by the Unanimous Consent of the States present the Seventeenth Day of September in the Year of our Lord one thousand seven hundred and Eighty seven and of the Independance of the United States of America the Twelfth In witness whereof We have hereunto subscribed our Names.',
    canonicalCitation: 'U.S. Const. art. VII',
    order: 70,
    topicTags: ['ratification', 'founding'],
  },

  // ════════════════════════════════════════════════════════════════════════
  // BILL OF RIGHTS (Amendments I–X) – Ratified December 15, 1791
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'us-const-amend1',
    documentId: 'us-constitution',
    title: 'First Amendment – Religion, Speech, Press, Assembly, Petition',
    number: 'Amend. I',
    text: 'Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.',
    canonicalCitation: 'U.S. Const. amend. I',
    order: 101,
    effectiveDate: '1791-12-15',
    topicTags: ['free-speech', 'freedom-of-religion', 'freedom-of-press', 'right-to-assemble', 'right-to-petition'],
  },
  {
    id: 'us-const-amend2',
    documentId: 'us-constitution',
    title: 'Second Amendment – Right to Bear Arms',
    number: 'Amend. II',
    text: 'A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.',
    canonicalCitation: 'U.S. Const. amend. II',
    order: 102,
    effectiveDate: '1791-12-15',
    topicTags: ['right-to-bear-arms', 'militia'],
  },
  {
    id: 'us-const-amend3',
    documentId: 'us-constitution',
    title: 'Third Amendment – Quartering of Soldiers',
    number: 'Amend. III',
    text: 'No Soldier shall, in time of peace be quartered in any house, without the consent of the Owner, nor in time of war, but in a manner to be prescribed by law.',
    canonicalCitation: 'U.S. Const. amend. III',
    order: 103,
    effectiveDate: '1791-12-15',
    topicTags: ['quartering', 'property-rights'],
  },
  {
    id: 'us-const-amend4',
    documentId: 'us-constitution',
    title: 'Fourth Amendment – Search and Seizure',
    number: 'Amend. IV',
    text: 'The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized.',
    canonicalCitation: 'U.S. Const. amend. IV',
    order: 104,
    effectiveDate: '1791-12-15',
    topicTags: ['search-and-seizure', 'privacy', 'warrants', 'probable-cause'],
  },
  {
    id: 'us-const-amend5',
    documentId: 'us-constitution',
    title: 'Fifth Amendment – Grand Jury, Double Jeopardy, Self-Incrimination, Due Process, Takings',
    number: 'Amend. V',
    text: 'No person shall be held to answer for a capital, or otherwise infamous crime, unless on a presentment or indictment of a Grand Jury, except in cases arising in the land or naval forces, or in the Militia, when in actual service in time of War or public danger; nor shall any person be subject for the same offence to be twice put in jeopardy of life or limb; nor shall be compelled in any criminal case to be a witness against himself, nor be deprived of life, liberty, or property, without due process of law; nor shall private property be taken for public use, without just compensation.',
    canonicalCitation: 'U.S. Const. amend. V',
    order: 105,
    effectiveDate: '1791-12-15',
    topicTags: ['due-process', 'double-jeopardy', 'self-incrimination', 'eminent-domain', 'grand-jury'],
  },
  {
    id: 'us-const-amend6',
    documentId: 'us-constitution',
    title: 'Sixth Amendment – Criminal Prosecution Rights',
    number: 'Amend. VI',
    text: 'In all criminal prosecutions, the accused shall enjoy the right to a speedy and public trial, by an impartial jury of the State and district wherein the crime shall have been committed, which district shall have been previously ascertained by law, and to be informed of the nature and cause of the accusation; to be confronted with the witnesses against him; to have compulsory process for obtaining witnesses in his favor, and to have the Assistance of Counsel for his defence.',
    canonicalCitation: 'U.S. Const. amend. VI',
    order: 106,
    effectiveDate: '1791-12-15',
    topicTags: ['right-to-counsel', 'speedy-trial', 'jury-trial', 'confrontation-clause'],
  },
  {
    id: 'us-const-amend7',
    documentId: 'us-constitution',
    title: 'Seventh Amendment – Civil Trial Rights',
    number: 'Amend. VII',
    text: 'In Suits at common law, where the value in controversy shall exceed twenty dollars, the right of trial by jury shall be preserved, and no fact tried by a jury, shall be otherwise re-examined in any Court of the United States, than according to the rules of the common law.',
    canonicalCitation: 'U.S. Const. amend. VII',
    order: 107,
    effectiveDate: '1791-12-15',
    topicTags: ['jury-trial', 'civil-rights'],
  },
  {
    id: 'us-const-amend8',
    documentId: 'us-constitution',
    title: 'Eighth Amendment – Cruel and Unusual Punishment',
    number: 'Amend. VIII',
    text: 'Excessive bail shall not be required, nor excessive fines imposed, nor cruel and unusual punishments inflicted.',
    canonicalCitation: 'U.S. Const. amend. VIII',
    order: 108,
    effectiveDate: '1791-12-15',
    topicTags: ['bail', 'cruel-and-unusual-punishment', 'criminal-justice'],
  },
  {
    id: 'us-const-amend9',
    documentId: 'us-constitution',
    title: 'Ninth Amendment – Unenumerated Rights',
    number: 'Amend. IX',
    text: 'The enumeration in the Constitution, of certain rights, shall not be construed to deny or disparage others retained by the people.',
    canonicalCitation: 'U.S. Const. amend. IX',
    order: 109,
    effectiveDate: '1791-12-15',
    topicTags: ['unenumerated-rights', 'retained-rights'],
  },
  {
    id: 'us-const-amend10',
    documentId: 'us-constitution',
    title: 'Tenth Amendment – Reserved Powers',
    number: 'Amend. X',
    text: 'The powers not delegated to the United States by the Constitution, nor prohibited by it to the States, are reserved to the States respectively, or to the people.',
    canonicalCitation: 'U.S. Const. amend. X',
    order: 110,
    effectiveDate: '1791-12-15',
    topicTags: ['federalism', 'reserved-powers', 'states-rights'],
  },

  // ════════════════════════════════════════════════════════════════════════
  // POST-BILL OF RIGHTS AMENDMENTS (XI–XXVII)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: 'us-const-amend11',
    documentId: 'us-constitution',
    title: 'Eleventh Amendment – Sovereign Immunity',
    number: 'Amend. XI',
    text: 'The Judicial power of the United States shall not be construed to extend to any suit in law or equity, commenced or prosecuted against one of the United States by Citizens of another State, or by Citizens or Subjects of any Foreign State.',
    canonicalCitation: 'U.S. Const. amend. XI',
    order: 111,
    effectiveDate: '1795-02-07',
    topicTags: ['sovereign-immunity', 'judicial-power'],
  },
  {
    id: 'us-const-amend12',
    documentId: 'us-constitution',
    title: 'Twelfth Amendment – Electoral College Procedures',
    number: 'Amend. XII',
    text: 'The Electors shall meet in their respective states and vote by ballot for President and Vice-President, one of whom, at least, shall not be an inhabitant of the same state with themselves; they shall name in their ballots the person voted for as President, and in distinct ballots the person voted for as Vice-President, and they shall make distinct lists of all persons voted for as President, and of all persons voted for as Vice-President, and of the number of votes for each, which lists they shall sign and certify, and transmit sealed to the seat of the government of the United States, directed to the President of the Senate;—the President of the Senate shall, in the presence of the Senate and House of Representatives, open all the certificates and the votes shall then be counted;—The person having the greatest number of votes for President, shall be the President, if such number be a majority of the whole number of Electors appointed; and if no person have such majority, then from the persons having the highest numbers not exceeding three on the list of those voted for as President, the House of Representatives shall choose immediately, by ballot, the President. But in choosing the President, the votes shall be taken by states, the representation from each state having one vote; a quorum for this purpose shall consist of a member or members from two-thirds of the states, and a majority of all the states shall be necessary to a choice. And if the House of Representatives shall not choose a President whenever the right of choice shall devolve upon them, before the fourth day of March next following, then the Vice-President shall act as President, as in case of the death or other constitutional disability of the President.—The person having the greatest number of votes as Vice-President, shall be the Vice-President, if such number be a majority of the whole number of Electors appointed, and if no person have a majority, then from the two highest numbers on the list, the Senate shall choose the Vice-President; a quorum for the purpose shall consist of two-thirds of the whole number of Senators, and a majority of the whole number shall be necessary to a choice. But no person constitutionally ineligible to the office of President shall be eligible to that of Vice-President of the United States.',
    canonicalCitation: 'U.S. Const. amend. XII',
    order: 112,
    effectiveDate: '1804-06-15',
    topicTags: ['electoral-college', 'presidential-election'],
  },
  {
    id: 'us-const-amend13',
    documentId: 'us-constitution',
    title: 'Thirteenth Amendment – Abolition of Slavery',
    number: 'Amend. XIII',
    text: 'Section 1. Neither slavery nor involuntary servitude, except as a punishment for crime whereof the party shall have been duly convicted, shall exist within the United States, or any place subject to their jurisdiction.\n\nSection 2. Congress shall have power to enforce this article by appropriate legislation.',
    canonicalCitation: 'U.S. Const. amend. XIII',
    order: 113,
    effectiveDate: '1865-12-06',
    topicTags: ['abolition-of-slavery', 'civil-rights', 'reconstruction'],
  },
  {
    id: 'us-const-amend14',
    documentId: 'us-constitution',
    title: 'Fourteenth Amendment – Citizenship, Due Process, Equal Protection',
    number: 'Amend. XIV',
    text: 'Section 1. All persons born or naturalized in the United States, and subject to the jurisdiction thereof, are citizens of the United States and of the State wherein they reside. No State shall make or enforce any law which shall abridge the privileges or immunities of citizens of the United States; nor shall any State deprive any person of life, liberty, or property, without due process of law; nor deny to any person within its jurisdiction the equal protection of the laws.\n\nSection 2. Representatives shall be apportioned among the several States according to their respective numbers, counting the whole number of persons in each State, excluding Indians not taxed.\n\nSection 3. No person shall be a Senator or Representative in Congress, or elector of President and Vice-President, or hold any office, civil or military, under the United States, or under any State, who, having previously taken an oath, as a member of Congress, or as an officer of the United States, or as a member of any State legislature, or as an executive or judicial officer of any State, to support the Constitution of the United States, shall have engaged in insurrection or rebellion against the same, or given aid or comfort to the enemies thereof. But Congress may by a vote of two-thirds of each House, remove such disability.\n\nSection 4. The validity of the public debt of the United States, authorized by law, including debts incurred for payment of pensions and bounties for services in suppressing insurrection or rebellion, shall not be questioned.\n\nSection 5. The Congress shall have the power to enforce, by appropriate legislation, the provisions of this article.',
    canonicalCitation: 'U.S. Const. amend. XIV',
    order: 114,
    effectiveDate: '1868-07-09',
    topicTags: ['due-process', 'equal-protection', 'citizenship', 'incorporation-doctrine', 'reconstruction'],
  },
  {
    id: 'us-const-amend15',
    documentId: 'us-constitution',
    title: 'Fifteenth Amendment – Right to Vote (Race)',
    number: 'Amend. XV',
    text: 'Section 1. The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of race, color, or previous condition of servitude.\n\nSection 2. The Congress shall have the power to enforce this article by appropriate legislation.',
    canonicalCitation: 'U.S. Const. amend. XV',
    order: 115,
    effectiveDate: '1870-02-03',
    topicTags: ['voting-rights', 'civil-rights', 'reconstruction'],
  },
  {
    id: 'us-const-amend16',
    documentId: 'us-constitution',
    title: 'Sixteenth Amendment – Income Tax',
    number: 'Amend. XVI',
    text: 'The Congress shall have power to lay and collect taxes on incomes, from whatever source derived, without apportionment among the several States, and without regard to any census or enumeration.',
    canonicalCitation: 'U.S. Const. amend. XVI',
    order: 116,
    effectiveDate: '1913-02-03',
    topicTags: ['taxing-power', 'income-tax'],
  },
  {
    id: 'us-const-amend17',
    documentId: 'us-constitution',
    title: 'Seventeenth Amendment – Direct Election of Senators',
    number: 'Amend. XVII',
    text: 'The Senate of the United States shall be composed of two Senators from each State, elected by the people thereof, for six years; and each Senator shall have one vote. The electors in each State shall have the qualifications requisite for electors of the most numerous branch of the State legislatures.\n\nWhen vacancies happen in the representation of any State in the Senate, the executive authority of such State shall issue writs of election to fill such vacancies: Provided, That the legislature of any State may empower the executive thereof to make temporary appointments until the people fill the vacancies by election as the legislature may direct.\n\nThis amendment shall not be so construed as to affect the election or term of any Senator chosen before it becomes valid as part of the Constitution.',
    canonicalCitation: 'U.S. Const. amend. XVII',
    order: 117,
    effectiveDate: '1913-04-08',
    topicTags: ['senate', 'direct-election', 'popular-sovereignty'],
  },
  {
    id: 'us-const-amend18',
    documentId: 'us-constitution',
    title: 'Eighteenth Amendment – Prohibition (Repealed)',
    number: 'Amend. XVIII',
    text: 'Section 1. After one year from the ratification of this article the manufacture, sale, or transportation of intoxicating liquors within, the importation thereof into, or the exportation thereof from the United States and all territory subject to the jurisdiction thereof for beverage purposes is hereby prohibited.\n\nSection 2. The Congress and the several States shall have concurrent power to enforce this article by appropriate legislation.\n\nSection 3. This article shall be inoperative unless it shall have been ratified as an amendment to the Constitution by the legislatures of the several States, as provided in the Constitution, within seven years from the date of the submission hereof to the States by the Congress.',
    canonicalCitation: 'U.S. Const. amend. XVIII (repealed)',
    order: 118,
    effectiveDate: '1919-01-16',
    amendedDate: '1933-12-05',
    topicTags: ['prohibition', 'repealed-amendment'],
  },
  {
    id: 'us-const-amend19',
    documentId: 'us-constitution',
    title: 'Nineteenth Amendment – Women\'s Suffrage',
    number: 'Amend. XIX',
    text: 'The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of sex.\n\nCongress shall have power to enforce this article by appropriate legislation.',
    canonicalCitation: 'U.S. Const. amend. XIX',
    order: 119,
    effectiveDate: '1920-08-18',
    topicTags: ['voting-rights', 'womens-suffrage', 'equal-rights'],
  },
  {
    id: 'us-const-amend20',
    documentId: 'us-constitution',
    title: 'Twentieth Amendment – Presidential Term and Succession',
    number: 'Amend. XX',
    text: 'Section 1. The terms of the President and the Vice President shall end at noon on the 20th day of January, and the terms of Senators and Representatives at noon on the 3d day of January, of the years in which such terms would have ended if this article had not been ratified; and the terms of their successors shall then begin.\n\nSection 2. The Congress shall assemble at least once in every year, and such meeting shall begin at noon on the 3d day of January, unless they shall by law appoint a different day.\n\nSection 3. If, at the time fixed for the beginning of the term of the President, the President elect shall have died, the Vice President elect shall become President. If a President shall not have been chosen before the time fixed for the beginning of his term, or if the President elect shall have failed to qualify, then the Vice President elect shall act as President until a President shall have qualified; and the Congress may by law provide for the case wherein neither a President elect nor a Vice President shall have qualified, declaring who shall then act as President, or the manner in which one who is to act shall be selected, and such person shall act accordingly until a President or Vice President shall have qualified.\n\nSection 4. The Congress may by law provide for the case of the death of any of the persons from whom the House of Representatives may choose a President whenever the right of choice shall have devolved upon them, and for the case of the death of any of the persons from whom the Senate may choose a Vice President whenever the right of choice shall have devolved upon them.\n\nSection 5. Sections 1 and 2 shall take effect on the 15th day of October following the ratification of this article.\n\nSection 6. This article shall be inoperative unless it shall have been ratified as an amendment to the Constitution by the legislatures of three-fourths of the several States within seven years from the date of its submission.',
    canonicalCitation: 'U.S. Const. amend. XX',
    order: 120,
    effectiveDate: '1933-01-23',
    topicTags: ['presidential-succession', 'terms-of-office'],
  },
  {
    id: 'us-const-amend21',
    documentId: 'us-constitution',
    title: 'Twenty-first Amendment – Repeal of Prohibition',
    number: 'Amend. XXI',
    text: 'Section 1. The eighteenth article of amendment to the Constitution of the United States is hereby repealed.\n\nSection 2. The transportation or importation into any State, Territory, or Possession of the United States for delivery or use therein of intoxicating liquors, in violation of the laws thereof, is hereby prohibited.\n\nSection 3. This article shall be inoperative unless it shall have been ratified as an amendment to the Constitution by conventions in the several States, as provided in the Constitution, within seven years from the date of the submission hereof to the States by the Congress.',
    canonicalCitation: 'U.S. Const. amend. XXI',
    order: 121,
    effectiveDate: '1933-12-05',
    topicTags: ['repeal-of-prohibition', 'state-power'],
  },
  {
    id: 'us-const-amend22',
    documentId: 'us-constitution',
    title: 'Twenty-second Amendment – Presidential Term Limits',
    number: 'Amend. XXII',
    text: 'Section 1. No person shall be elected to the office of the President more than twice, and no person who has held the office of President, or acted as President, for more than two years of a term to which some other person was elected President shall be elected to the office of President more than once. But this Article shall not apply to any person holding the office of President when this Article was proposed by Congress, and shall not prevent any person who may be holding the office of President, or acting as President, during the term within which this Article becomes operative from holding the office of President or acting as President during the remainder of such term.\n\nSection 2. This article shall be inoperative unless it shall have been ratified as an amendment to the Constitution by the legislatures of three-fourths of the several States within seven years from the date of its submission to the States by the Congress.',
    canonicalCitation: 'U.S. Const. amend. XXII',
    order: 122,
    effectiveDate: '1951-02-27',
    topicTags: ['term-limits', 'presidential-power'],
  },
  {
    id: 'us-const-amend23',
    documentId: 'us-constitution',
    title: 'Twenty-third Amendment – D.C. Electoral Votes',
    number: 'Amend. XXIII',
    text: 'Section 1. The District constituting the seat of Government of the United States shall appoint in such manner as Congress may direct: A number of electors of President and Vice President equal to the whole number of Senators and Representatives in Congress to which the District would be entitled if it were a State, but in no event more than the least populous State; they shall be in addition to those appointed by the States, but they shall be considered, for the purposes of the election of President and Vice President, to be electors appointed by a State; and they shall meet in the District and perform such duties as provided by the twelfth article of amendment.\n\nSection 2. The Congress shall have power to enforce this article by appropriate legislation.',
    canonicalCitation: 'U.S. Const. amend. XXIII',
    order: 123,
    effectiveDate: '1961-03-29',
    topicTags: ['electoral-college', 'district-of-columbia', 'voting-rights'],
  },
  {
    id: 'us-const-amend24',
    documentId: 'us-constitution',
    title: 'Twenty-fourth Amendment – Abolition of Poll Tax',
    number: 'Amend. XXIV',
    text: 'Section 1. The right of citizens of the United States to vote in any primary or other election for President or Vice President, for electors for President or Vice President, or for Senator or Representative in Congress, shall not be denied or abridged by the United States or any State by reason of failure to pay any poll tax or other tax.\n\nSection 2. The Congress shall have power to enforce this article by appropriate legislation.',
    canonicalCitation: 'U.S. Const. amend. XXIV',
    order: 124,
    effectiveDate: '1964-01-23',
    topicTags: ['voting-rights', 'poll-tax', 'civil-rights'],
  },
  {
    id: 'us-const-amend25',
    documentId: 'us-constitution',
    title: 'Twenty-fifth Amendment – Presidential Disability and Succession',
    number: 'Amend. XXV',
    text: 'Section 1. In case of the removal of the President from office or of his death or resignation, the Vice President shall become President.\n\nSection 2. Whenever there is a vacancy in the office of the Vice President, the President shall nominate a Vice President who shall take office upon confirmation by a majority vote of both Houses of Congress.\n\nSection 3. Whenever the President transmits to the President pro tempore of the Senate and the Speaker of the House of Representatives his written declaration that he is unable to discharge the powers and duties of his office, and until he transmits to them a written declaration to the contrary, such powers and duties shall be discharged by the Vice President as Acting President.\n\nSection 4. Whenever the Vice President and a majority of either the principal officers of the executive departments or of such other body as Congress may by law provide, transmit to the President pro tempore of the Senate and the Speaker of the House of Representatives their written declaration that the President is unable to discharge the powers and duties of his office, the Vice President shall immediately assume the powers and duties of the office as Acting President. Thereafter, when the President transmits to the President pro tempore of the Senate and the Speaker of the House of Representatives his written declaration that no inability exists, he shall resume the powers and duties of his office unless the Vice President and a majority of either the principal officers of the executive department or of such other body as Congress may by law provide, transmit within four days to the President pro tempore of the Senate and the Speaker of the House of Representatives their written declaration that the President is unable to discharge the powers and duties of his office. Thereupon Congress shall decide the issue, assembling within forty-eight hours for that purpose if not in session. If the Congress, within twenty-one days after receipt of the latter written declaration, or, if Congress is not in session, within twenty-one days after Congress is required to assemble, determines by two-thirds vote of both Houses that the President is unable to discharge the powers and duties of his office, the Vice President shall continue to discharge the same as Acting President; otherwise, the President shall resume the powers and duties of his office.',
    canonicalCitation: 'U.S. Const. amend. XXV',
    order: 125,
    effectiveDate: '1967-02-10',
    topicTags: ['presidential-succession', 'presidential-disability'],
  },
  {
    id: 'us-const-amend26',
    documentId: 'us-constitution',
    title: 'Twenty-sixth Amendment – Voting Age (18)',
    number: 'Amend. XXVI',
    text: 'Section 1. The right of citizens of the United States, who are eighteen years of age or older, to vote shall not be denied or abridged by the United States or by any State on account of age.\n\nSection 2. The Congress shall have power to enforce this article by appropriate legislation.',
    canonicalCitation: 'U.S. Const. amend. XXVI',
    order: 126,
    effectiveDate: '1971-07-01',
    topicTags: ['voting-rights', 'voting-age'],
  },
  {
    id: 'us-const-amend27',
    documentId: 'us-constitution',
    title: 'Twenty-seventh Amendment – Congressional Pay',
    number: 'Amend. XXVII',
    text: 'No law, varying the compensation for the services of the Senators and Representatives, shall take effect, until an election of Representatives shall have intervened.',
    canonicalCitation: 'U.S. Const. amend. XXVII',
    order: 127,
    effectiveDate: '1992-05-07',
    topicTags: ['congressional-compensation', 'accountability'],
  },
]

/**
 * Cross-reference mappings between federal constitutional provisions
 * and common state constitutional equivalents (by topic).
 */
export const federalStateOverlayMappings: {
  federalSectionId: string
  stateTopicMatch: string
  comparisonNotes: string
}[] = [
  {
    federalSectionId: 'us-const-amend1',
    stateTopicMatch: 'Freedom of Religion',
    comparisonNotes: 'Most state constitutions contain parallel protections for religious liberty, sometimes with broader or narrower language than the First Amendment. State provisions may include explicit protections not found in the federal text.',
  },
  {
    federalSectionId: 'us-const-amend1',
    stateTopicMatch: 'Freedom of Speech and Press',
    comparisonNotes: 'State constitutions typically provide free speech protections that parallel the First Amendment. Some states, such as California, have been interpreted to provide broader free speech protections than the federal Constitution.',
  },
  {
    federalSectionId: 'us-const-amend4',
    stateTopicMatch: 'Due Process',
    comparisonNotes: 'State due process clauses often mirror the Fourth and Fourteenth Amendments. Some states provide additional privacy protections beyond federal constitutional minimums.',
  },
  {
    federalSectionId: 'us-const-amend14',
    stateTopicMatch: 'Bill of Rights - Fundamental Rights',
    comparisonNotes: 'The Fourteenth Amendment\'s Equal Protection and Due Process Clauses set a federal floor. State bills of rights may enumerate additional or more specific protections.',
  },
  {
    federalSectionId: 'us-const-art1',
    stateTopicMatch: 'Article II - Legislative Power',
    comparisonNotes: 'Both federal and state constitutions vest legislative power in a bicameral legislature (except Nebraska, which has a unicameral legislature). State legislatures are subject to both federal and state constitutional limits.',
  },
  {
    federalSectionId: 'us-const-art2',
    stateTopicMatch: 'Article III - Executive Power',
    comparisonNotes: 'State executive power structures typically parallel the federal model with a governor as chief executive, though most states elect additional executive officers independently (attorney general, secretary of state, etc.).',
  },
]
